version: "3"
services:
  db: 
    image: mysql:5.7
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./my-data:/var/lib/mysql
  redis:
    image: 'redis:5-alpine'
    command: redis-server --port 6378 --appendonly yes
    ports:
      - '6378:6378'
    volumes:
      - './redis-data:/data'
  sidekiq:
    depends_on:
      - redis
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    volumes:
      - '.:/app'
  elasticsearch:
    image: elasticsearch:5.4.0-alpine
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data
  web:
    build: .
    command: bash -c "sh ./wait_for_elasticsearch.sh elasticsearch:9200 && sh ./wait_for_service.sh db 3306 && sh ./entrypoint.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - sidekiq
      - elasticsearch
      - db
volumes:
  my-data:
  redis-data:
  
